[package]
name = "craked"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lolcat = "1.5.0"
colored = "2.0"
rand = "*"
imap = "*"
native-tls = "0.2.11"
text2art = "1.0.2"
rayon = "*"